CREATE TABLE IF NOT EXISTS urls (
    id BIGINT PRIMARY KEY,
    long_url TEXT NOT NULL UNIQUE,
    short_url VARCHAR(20) UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_short_url ON urls(short_url);